/* eslint-disable react-hooks/set-state-in-effect */
"use client";

import { CREATE_PERMISSION, CREATE_ROLE, DELETE_PERMISSION, DELETE_ROLE, GET_ALL_PERMISSIONS, GET_ALL_ROLES, UPDATE_PERMISSION, UPDATE_ROLE } from "@/utils/api";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { EmptyState, fieldClass, LoadingState, Modal, Notice, PageHeader, requestApi, SearchBar } from "./AdminUI";

type Permission = { _id: string; key: string; description?: string; module?: string };
type Role = { _id: string; user_type: string; description?: string; permissions?: Permission[] };

export default function AccessManager() {
  const [tab, setTab] = useState<"roles" | "permissions">("roles"); const [roles, setRoles] = useState<Role[]>([]); const [permissions, setPermissions] = useState<Permission[]>([]); const [search, setSearch] = useState(""); const [moduleName, setModuleName] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [editRole, setEditRole] = useState<Role | "new" | null>(null); const [editPermission, setEditPermission] = useState<Permission | "new" | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const query = new URLSearchParams({ page: "1", limit: "100" }); if (search) query.set("search", search); if (moduleName) query.set("module", moduleName); const [rolePayload, permissionPayload] = await Promise.all([requestApi(GET_ALL_ROLES), requestApi(`${GET_ALL_PERMISSIONS}?${query}`)]); setRoles(rolePayload.data || []); setPermissions(permissionPayload.data?.data || []); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load access control."); } finally { setLoading(false); } }, [moduleName, search]);
  useEffect(() => { load(); }, [load]);
  async function remove(kind: "role" | "permission", id: string, label: string) { if (!window.confirm(`Delete ${label}?`)) return; setError(""); setSuccess(""); try { const payload = await requestApi(kind === "role" ? DELETE_ROLE : DELETE_PERMISSION, { method: "DELETE", body: JSON.stringify(kind === "role" ? { roleId: id } : { permissionId: id }) }); setSuccess(payload.message); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Delete failed."); } }
  return <>
    <PageHeader eyebrow="Security" title="Access control" description="Maintain the project’s role and permission records and assign permissions to non-admin roles." action={<button className="btn-primary" onClick={() => tab === "roles" ? setEditRole("new") : setEditPermission("new")}>Add {tab === "roles" ? "role" : "permission"}</button>} />
    <div className="admin-tabs"><button className={tab === "roles" ? "active" : ""} onClick={() => setTab("roles")}>Roles</button><button className={tab === "permissions" ? "active" : ""} onClick={() => setTab("permissions")}>Permissions</button></div>
    {success && <Notice kind="success">{success}</Notice>}{error && <Notice>{error}</Notice>}
    {tab === "permissions" && <SearchBar value={search} onChange={setSearch} placeholder="Search key or description"><input className="admin-filter" value={moduleName} onChange={(e) => setModuleName(e.target.value)} placeholder="Module" /></SearchBar>}
    {loading ? <LoadingState label="Loading access control…" /> : tab === "roles" ? roles.length === 0 ? <EmptyState title="No roles configured" body="Add a role to get started." /> : <div className="grid gap-5 lg:grid-cols-2">{roles.map((role) => <article className="admin-card p-5" key={role._id}><div className="flex items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-[0.15em] ui-accent">Role</p><h2 className="text-headline-md ui-heading capitalize">{role.user_type}</h2></div><span className="admin-badge">{role.permissions?.length || 0} permissions</span></div><p className="mt-3 ui-copy">{role.description || "No description"}</p><div className="mt-4 flex flex-wrap gap-2">{role.permissions?.slice(0, 6).map((permission) => <span className="admin-chip" key={permission._id}>{permission.key}</span>)}{(role.permissions?.length || 0) > 6 && <span className="admin-chip">+{(role.permissions?.length || 0) - 6}</span>}</div><div className="mt-5 flex gap-2"><button className="admin-button-secondary flex-1" onClick={() => setEditRole(role)}>Edit & assign</button><button className="admin-button-danger" onClick={() => remove("role", role._id, `role “${role.user_type}”`)}>Delete</button></div></article>)}</div> : permissions.length === 0 ? <EmptyState title="No permissions found" body="Try another search or create a permission." /> : <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Key</th><th>Module</th><th>Description</th><th>Actions</th></tr></thead><tbody>{permissions.map((permission) => <tr key={permission._id}><td><strong>{permission.key}</strong></td><td>{permission.module || "—"}</td><td>{permission.description || "—"}</td><td><div className="flex gap-2"><button className="admin-button-secondary" onClick={() => setEditPermission(permission)}>Edit</button><button className="admin-button-danger" onClick={() => remove("permission", permission._id, `permission “${permission.key}”`)}>Delete</button></div></td></tr>)}</tbody></table></div>}
    {editRole && <RoleForm role={editRole === "new" ? undefined : editRole} permissions={permissions} onClose={() => setEditRole(null)} onSaved={(message) => { setEditRole(null); setSuccess(message); load(); }} />}
    {editPermission && <PermissionForm permission={editPermission === "new" ? undefined : editPermission} onClose={() => setEditPermission(null)} onSaved={(message) => { setEditPermission(null); setSuccess(message); load(); }} />}
  </>;
}

function RoleForm({ role, permissions, onClose, onSaved }: { role?: Role; permissions: Permission[]; onClose: () => void; onSaved: (message: string) => void }) {
  const [type, setType] = useState(role?.user_type || "sales"); const [description, setDescription] = useState(role?.description || ""); const [selected, setSelected] = useState<string[]>(role?.permissions?.map((permission) => permission._id) || []); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  function toggle(id: string) { setSelected((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]); }
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const body = { user_type: type, description, permissions: selected }; const payload = await requestApi(role ? UPDATE_ROLE : CREATE_ROLE, { method: role ? "PATCH" : "POST", body: JSON.stringify(role ? { roleId: role._id, ...body } : body) }); onSaved(payload.message); } catch (err) { setError(err instanceof Error ? err.message : "Unable to save role."); } finally { setBusy(false); } }
  const modules = Object.groupBy(permissions, (permission) => permission.module || "Other");
  return <Modal title={`${role ? "Edit" : "Add"} role`} onClose={onClose}><form onSubmit={submit} className="space-y-5">{error && <Notice>{error}</Notice>}<label className="admin-label">Role type<select className={fieldClass} value={type} onChange={(e) => setType(e.target.value)}><option>user</option><option>sales</option><option>admin</option></select></label><label className="admin-label">Description<input className={fieldClass} maxLength={255} value={description} onChange={(e) => setDescription(e.target.value)} /></label><fieldset disabled={type === "admin"}><legend className="admin-label mb-3">Permissions {type === "admin" && <span className="normal-case font-normal ui-muted">(admins always receive all)</span>}</legend><div className="space-y-4 max-h-72 overflow-auto border border-surface rounded-lg p-4">{Object.entries(modules).map(([module, values]) => <div key={module}><p className="text-xs uppercase tracking-[0.15em] ui-accent mb-2">{module}</p><div className="grid sm:grid-cols-2 gap-2">{values?.map((permission) => <label className="admin-check" key={permission._id}><input type="checkbox" checked={type === "admin" || selected.includes(permission._id)} onChange={() => toggle(permission._id)} /><span>{permission.key}</span></label>)}</div></div>)}</div></fieldset><div className="flex justify-end gap-3"><button type="button" className="admin-button-secondary" onClick={onClose}>Cancel</button><button className="btn-primary" disabled={busy}>{busy ? "Saving…" : "Save role"}</button></div></form></Modal>;
}

function PermissionForm({ permission, onClose, onSaved }: { permission?: Permission; onClose: () => void; onSaved: (message: string) => void }) {
  const [key, setKey] = useState(permission?.key || ""); const [description, setDescription] = useState(permission?.description || ""); const [moduleName, setModuleName] = useState(permission?.module || ""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const body = { key, description, module: moduleName }; const payload = await requestApi(permission ? UPDATE_PERMISSION : CREATE_PERMISSION, { method: permission ? "PATCH" : "POST", body: JSON.stringify(permission ? { permissionId: permission._id, ...body } : body) }); onSaved(payload.message); } catch (err) { setError(err instanceof Error ? err.message : "Unable to save permission."); } finally { setBusy(false); } }
  return <Modal title={`${permission ? "Edit" : "Add"} permission`} onClose={onClose}><form onSubmit={submit} className="space-y-5">{error && <Notice>{error}</Notice>}<label className="admin-label">Key<input className={fieldClass} required minLength={2} maxLength={100} value={key} onChange={(e) => setKey(e.target.value)} placeholder="module.action" /></label><label className="admin-label">Module<input className={fieldClass} maxLength={100} value={moduleName} onChange={(e) => setModuleName(e.target.value)} /></label><label className="admin-label">Description<textarea className={fieldClass} maxLength={255} rows={3} value={description} onChange={(e) => setDescription(e.target.value)} /></label><div className="flex justify-end gap-3"><button type="button" className="admin-button-secondary" onClick={onClose}>Cancel</button><button className="btn-primary" disabled={busy}>{busy ? "Saving…" : "Save permission"}</button></div></form></Modal>;
}
